### ISSUE TITLE
Does not work with node.js and typescript 2

### ISSUE THREAD

**Issue by spinwards** [loedeman/AutoMapper#25] opened 2017-02-01 23:08 UTC
The issue reported in #16 has not been addressed and is preventing me from using automapper-ts in a project. 

The most recent comment has the solution: 

> @staff0rd commented on Nov 22, 2016
> I found this also, but in node so thought it was a regression of #7, however it seems the fix was just to add the following to the bottom of automapper.d.ts;
> 
> `export = automapper;`
>
> After doing so I was able to properly import and execute automapper tasks using the following;
> 
>`import automapper = require("automapper-ts")`
> `automapper.createMap('ObjA', 'ObjB') // etc`

I made the changes locally in my node_modules folder and can confirm that this allows the library to be imported as expected.

**Comment by valours** [comment] 2017-02-27 11:09
Hi @spinwards 
Do you have find better solution for using Automapper in your project ?

Thanks

**Comment by spinwards** [comment] 2017-03-01 21:35
I ended up writing a function to create my objects.

**Comment by loedeman** [comment] 2017-05-09 13:17
Hi @spinwards and @valours,

Since this item has been open for quite a while without getting a lot of attention, I am closing the issue.

The AutoMapperTS library has not been designed explicitly for use with node.js. Most users appear to have no problem using it, though. I am not using this library in any node.js project myself, therefore reproducing, and more importantly, fixing this in a clean way (using TypeScript) is not very easy for me.

Should you feel like fixing the problem, please feel free to create a PR. I will be happy to accept it ;) ...

Cheers, Bert

**Closed by loedeman** 2017-05-09 13:17 UTC
